require './db/migrations/create_pokemon.rb'
require './db/migrations/create_type.rb'
require './db/migrations/create_user_pokemon.rb'
require './db/migrations/create_pokemon_type.rb'
require './db/migrations/create_user.rb'